env:
  TERM: xterm-256color
  # set TERM_PROGRAM variable to work on MacOS
  # See MacOS zsh config in /etc/zshrc
  TERM_PROGRAM: alacritty

window:
  decorations: full

font:
  # configure initial size
  size: 18.0
  normal:
    # family: Hack Nerd Font
    # style: Regular
    family: FiraCode Nerd Font
    style: Light
    #family: Hack
    # family: Fira Code
    #family: monospace
    #family: Terminus (TTF)
    #family: Tlwg Mono
    #style: Bold

colors:
  # Default colors
  #primary:
  background: '#000000'
  foreground: '#eaeaea'
  dim_foreground: '#9a9a9a'
  bright_foreground: '#ffffff'

#background_opacity: 0.95
live_config_reload: true

selection:
  # save selection to clipboard automatically
  # like other terminals
  save_to_clipboard: true

key_bindings:
  - { key: T,   mods: Command, action: SpawnNewInstance }
  - { key: F,   mods: Command, action: SearchForward }
  - { key: B,   mods: Command, action: SearchBackward }
  - { key: Plus, mods: Command, action: IncreaseFontSize }
  - { key: Minus, mods: Command, action: DecreaseFontSize }
  - { key: 0, mods: Command, action: DecreaseFontSize }

  # map shift-CR so it's available on the terminal
  #  https://stackoverflow.com/a/42461580
  - { key: Return,   mods: Shift,   chars: "\x1b[13;2u" }
  - { key: Return,   mods: Control, chars: "\x1b[13;5u" }
