live_config_reload = true

[colors]
#background = "#000000"
#bright_foreground = "#ffffff"
#dim_foreground = "#9a9a9a"
#foreground = "#eaeaea"

[env]
TERM = "xterm-256color"
TERM_PROGRAM = "alacritty"

[font]
size = 18.0

[font.normal]
family = "FiraCode Nerd Font"
style = "Light"

[[keyboard.bindings]]
action = "SpawnNewInstance"
key = "T"
mods = "Command"

[[keyboard.bindings]]
action = "SearchForward"
key = "F"
mods = "Command"

[[keyboard.bindings]]
action = "SearchBackward"
key = "B"
mods = "Command"

[[keyboard.bindings]]
action = "IncreaseFontSize"
key = "Plus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = "Minus"
mods = "Command"

[[keyboard.bindings]]
action = "DecreaseFontSize"
key = 0
mods = "Command"

[[keyboard.bindings]]
chars = "\u001B[13;2u"
key = "Return"
mods = "Shift"

[[keyboard.bindings]]
chars = "\u001B[13;5u"
key = "Return"
mods = "Control"

[selection]
save_to_clipboard = true

[window]
decorations = "full"
