---
# aqua - Declarative CLI Version Manager
# https://aquaproj.github.io/
# checksum:
#   enabled: true
#   require_checksum: true
#   supported_envs:
#   - all
registries:
- type: standard
  ref: v4.196.0 # renovate: depName=aquaproj/aqua-registry
packages:
- name: Schniz/fnm@v1.37.1
- name: neovim/neovim@v0.10.0
- name: starship/starship@v1.19.0
- name: sharkdp/bat@v0.24.0
- name: dandavison/delta@0.17.0
